### ISSUE TITLE
Auto Gift & Auto Share

### ISSUE THREAD

**Issue by NoYouPickAUsername** [dankgrinder/dankgrinder#36] opened 2021-04-22 02:48 UTC
It needs to say yes afterwards to confirm sending the item or money to the master instance.

**Comment by ihavezerohealth** [comment] 2021-04-22 05:18
Use a custom command across all instances to avoid this:
pls settings confirm false
I think it's that, but just double check and please let me know!

**Comment by dankgrinder** [comment] 2021-04-22 10:39
Duplicate of #35, may or may not be automated in the future.

**Closed by dankgrinder** 2021-04-22 10:39 UTC
Labels: duplicate, question
