### ISSUE TITLE
Auto Blackjack

### ISSUE THREAD

**Issue by daaankm** [dankgrinder/dankgrinder#28] opened 2021-04-06 03:11 UTC
so im a little confused on how the auto blackjack works. when i turn it on, it checks the balance and starts to blackjack but the autobot doesnt respond with hit or stand, it just keeps typing "pls blackjack max" and blows your money. i checked the logs and it said await resume timed out for: pls blackjack max. could someone help me with this?

**Comment by Nevermind26** [comment] 2021-04-06 08:26
It started today only I have the same issue think something wrong just got to wait for the update I guess. Just put false for auto bj and run other cmds

**Comment by ihavezerohealth** [comment] 2021-04-06 08:34
The issue is there was an embed rewrite. Nice one Daunt.

**Comment by dankgrinder** [comment] 2021-04-06 11:17
Known issue. Will be fixed in the next update. Invisible characters were added in between every character in the username of the embed causing the handler to fail.

**Closed by dankgrinder** 2021-04-06 11:17 UTC
Labels: question
