### ISSUE TITLE
Oof last question 

### ISSUE THREAD

**Issue by empty8005** [dankgrinder/dankgrinder#56] opened 2021-05-25 06:32 UTC
I have clone tool in termux also edited it but I am unable to find which pkg I have to install so I can run config.yml also how to get token in android I serach on yt but i found nothing 😥🤧

**Comment by ihavezerohealth** [comment] 2021-05-25 06:47
bro you be crying over this shit?
then go cry lmao

**Comment by empty8005** [comment] 2021-05-25 08:32
> bro you be crying over this shit?
> then go cry lmao

Help pls

**Comment by dankgrinder** [comment] 2021-05-25 10:20
This is another duplicate of #51 and not relevant to Dank Grinder. Title is still very bad, contrary to my request. Stop making issues about this, I'm fed up

**Closed by dankgrinder** 2021-05-25 10:20 UTC
Labels: question
