### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by empty8005** [dankgrinder/dankgrinder#54] opened 2021-05-24 02:28 UTC
I just saw termux but I am more confused that I have can I run toll on it, should I have to do make from code option 🙇

**Comment by empty8005** [comment] 2021-05-24 04:44
I just wanted to know which steps I need to do before running tool in Android using termux.pls help

**Comment by ihavezerohealth** [comment] 2021-05-24 05:32
make from code wtf

**Comment by Maverish96** [comment] 2021-05-24 09:42
The bot is not responding for 'pls search' command. It just does 'pls search' and then even after dank memer responding with available options, the bot just does await_response_timeout and does not respond with a search place! Please fix this bug :)

**Comment by jsmoment** [comment] 2021-05-24 13:26
whats your discord ill try to help

**Comment by empty8005** [comment] 2021-05-24 13:37
empty8005#1753 @jsmoment send me friend request

**Comment by pani7777** [comment] 2021-05-24 18:49
the devs of dankgrinder dont support mobile but the community can help

**Comment by dankgrinder** [comment] 2021-05-24 23:54
Please make the title more descriptive if you open another issue. Also this is a duplicate of #51

**Closed by dankgrinder** 2021-05-24 23:54 UTC
Labels: question
